### PR TITLE
Fix functions' arguments colours

### PR DESCRIPTION
**Pull request by dempfi**
This PR brings back distinct purple colour of functions' arguments.

screen shot 2018-08-22 at 01 06 07

### CODE REVIEW

**Comment by blakeperdue** [comment]
Works for me using Dark theme. Only thing I noticed was it seemed to only bring back the colors for Javascript. Other filetypes like CSS, which used to have those colors, remain the same. But, I believe this PR was only scoped to functional arguments as the names suggests ;)

screen shot 2018-08-21 at 8 59 32 pm

**Comment by alexsasharegan** [comment]
I'm not sure how this will go purple on dark. The change-set shows a yellow color for ayu dark.

image

**Comment by dempfi** [comment]
@teabyii, @pahen can you please review and (possibly) merge this? :)

**Comment by pahen** [comment]
It seems to only affect TypeScript. Is this intentional? Arguments in JavaScript is still white.

screen shot 2018-08-29 at 14 58 26

**Comment by dempfi** [comment]
@pahen do you use some kind of custom syntax highlighting for javascript? Because for me with default javascript syntax highlighting arguments are purple.

**Comment by pahen** [comment]
Yes, I used [Babel ES6/ES7](https://github.com/dzannotti/vscode-babel/). I disabled that and it seems to work now :)

**Comment by pahen** [comment]
Thanks for your contribution! Merged and published the extension now :)

**Pull request merged**
