### PR TITLE
Theming for the VSCode 1.13 release

### LINKED ISSUE #12: Tree selection inactive color not visible
Click on some tree, like the git changes -> click on the editor. You can not see what is inactivly selected in the tree.

### LINKED ISSUE #13: Change status bar highlight
Steps to reproduce:
1. Use Ayu Mirage
2. Press Ctrl+M
You'll see green color on status bar, and 'Tab moves focus' is written there, which is barely visible. I think it isn't colored by you. Please provide a color to it for all themes.
3. Press Ctrl+M to turn it off

### LINKED ISSUE #14: Use correct colors for input validation
screen shot 2017-05-22 at 13 21 46 png

These keys are available to style this:
```
inputValidation.infoBackground
inputValidation.infoBorder
inputValidation.warningBackground
inputValidation.warningBorder
inputValidation.errorBackground
inputValidation.errorBorder
```

### LINKED ISSUE #15: Add border between file manager and editor
screen shot 2017-05-24 at 2 40 31 pm

There is no border between the file manager and editor. This is visually jarring and unappealing.

### LINKED ISSUE #16: Change the color of warning/error squiggles
See https://github.com/Microsoft/vscode/issues/9819

### PR DESCRIPTION
**Pull request by pahen**
This PR fixes a couple of issues. Most of the stuff are only supported in the Insiders build so we should probably wait with publishing a new release of the theme until VSCode 1.13 has been released.

These are the new theming colors added in 1.13: https://github.com/Microsoft/vscode/issues/27445

Fixes #12

Active:
screen shot 2017-05-25 at 19 24 07

Inactive:
screen shot 2017-05-25 at 19 24 27

Fixes #13

screen shot 2017-05-25 at 19 25 55

Fixes #14

screen shot 2017-05-25 at 19 26 25

Fixes #15

screen shot 2017-05-25 at 19 27 10

Fixes #16

screen shot 2017-05-25 at 19 28 17

### CODE REVIEW

**Comment by pahen** [comment]
Changed back to use old color for section headers in the sidebar:

screen shot 2017-05-29 at 18 12 27

**Comment by pahen** [comment]
Added theming of welcome page and interactive playground now too.

screen shot 2017-05-30 at 17 13 29

screen shot 2017-05-30 at 17 13 52

**Comment by pahen** [comment]
Have you had time to test it @teabyii ?

**Comment by pahen** [comment]
Here's a package if someone would like to try it with the latest Insiders build of VSCode. https://www.dropbox.com/s/2wao51jp31qh4mo/ayu-0.3.1.vsix?dl=1

**Comment by pahen** [comment]
VSCode 1.13 has been released now. See https://code.visualstudio.com/updates/v1_13

So it would be awesome if you could have a look at this PR and maybe create a new release of the theme @teabyii :)

**Comment by teabyii** [comment]
Sorry，I am busy recently. I will make it as soon as possible. Thank you very much.

**Comment by pahen** [comment]
No problem! Here are updated screenshoots for the themes too:

screen shot 2017-06-09 at 08 47 54
screen shot 2017-06-09 at 08 48 04
screen shot 2017-06-09 at 08 48 15

**Comment by pahen** [comment]
Would be nice to have this out soon @teabyii :)

**Comment by pahen** [comment]
Thanks! :)

**Pull request merged**
