### PR TITLE
Adjust colors of interface elements, logo and add hero

### PR DESCRIPTION
**Pull request by dempfi**
Hi @teabyii I'm very grateful for this lovely port. I use it personally when I do TypeScript coding and I want to help to improve this project.

**Changes:**
- Updated logo that is shown in vs market(previous one was misaligned and blurry);
- Added hero to match ayu for vim and main theme, you're welcome to remove this if you don't like it 😉;
- Changed background for active tab;
- Added border to titlebar and statusbar;
- Other small improvements for inputs and such.

### CODE REVIEW

**Comment by pahen** [comment]
Awesome! I like all the changes you did :) If @teabyii don't disagree I happily merge this.

**Comment by teabyii** [comment]
👍  @pahen

**Comment by pahen** [comment]
It would be awesome if you can update the screenshots in the README with the same images you used in the hero @dempfi :)

**Comment by pahen** [comment]
I released this as v0.7.0 now. Thanks for the help @dempfi :)

**Pull request merged**
