### PR TITLE
Use ayu-colors 4.0.0 (improved contrast)

### LINKED ISSUE #23: Allow for tweaking of non-highlight elements
I really like the Dark version of this theme, as it focuses me on the code and blends out a lot of the distractions from the rest of the editor.

However, a lot of the blended-out bits and bobs (e.g. unedited files in explorer or text in the bottom status bar) are now practically invisible on a lot of my screens, making it very hard to scan for a file or to see some of those details on first glance, without squinting:

image
image

I was wondering if we could get some configuration options to tweak this, say in this instance to lighten up the low-contrast elements?

### PR DESCRIPTION
**Pull request by pahen**
Fixes #23 

Updated screenshots:

screenshot 2017-08-05 00 38 33

screenshot 2017-08-05 00 38 49

screenshot 2017-08-05 00 39 03

### CODE REVIEW

**Comment by pahen** [comment]
Does the screenshot of dark theme looks good enough on your display now @batjko?

**Comment by batjko** [comment]
@pahen It's subtle, but definitely makes a difference, so I'd certainly be happy with this. 
Nice work. 👍

**Comment by pahen** [comment]
Let me know if you want to me to help you out as a maintainer of this theme if you're busy @teabyii

It would be awesome if we can move the repo https://github.com/ayu-theme to make it "official" if @dempfi and @k15a are interested in that.

**Comment by teabyii** [comment]
I has invited you to be the collaborator of this repo. Thank you for helping.

**Comment by pahen** [comment]
Thanks @teabyii :)

Can you give me permissions to publish to Extension Marketplace too?

I think the way to do it is explained here: https://github.com/Microsoft/vscode/issues/23801#issuecomment-292512395. The email you should add there as a contributor is `patrik.henningsson@gmail.com`.

**Comment by teabyii** [comment]
@pahen I've added you to the contributor in vscode marketplace. You can try to publish a new version.

**Comment by pahen** [comment]
Thanks! It worked :) Published 0.5.0 now 🎉

**Pull request merged**
